### ISSUE TITLE
Swiftnotes often crashes after tap on note field

### ISSUE THREAD

**Issue by Self-Perfection** [adrianchifor/Swiftnotes#18]
Swiftnotes crashes very often  when I tap on note text area in edit note view.
I use [version 3.1.3](https://f-droid.org/repo/com.moonpi.swiftnotes_10.apk) [from F-Droid](https://f-droid.org/repository/browse/?fdfilter=swiftnotes&fdid=com.moonpi.swiftnotes).
This essentially makes swiftnotes useless for me as the app crashes as soon as I try to enter contents for new note.

```
04-28 23:05:00.344 19285 19455 I ActivityManager: Start proc com.moonpi.swiftnotes for activity com.moonpi.swiftnotes/.MainActivity: pid=19576 uid=10051 gids={1028, 100000}
04-28 23:05:00.394 19206 19206 D alien_init: Set process(pid = 19576) score_adj as [0]
04-28 23:05:00.394 19285 19455 I ActivityManager: setOomScordAdjOfProcessesLocked pid = 19576, proc.oomScoreAdj = 0
04-28 23:05:00.924 19576 19576 D libEGL  : loaded /system/lib/egl/libEGL_adreno200.so
04-28 23:05:00.926 19576 19576 D libEGL  : loaded /system/lib/egl/libGLESv1_CM_adreno200.so
04-28 23:05:00.929 19576 19576 D libEGL  : loaded /system/lib/egl/libGLESv2_adreno200.so
04-28 23:05:00.935 19576 19576 I Adreno200-EGL: <qeglDrvAPI_eglInitialize:269>: EGL 1.4 QUALCOMM build:  (CL2961769)
04-28 23:05:00.935 19576 19576 I Adreno200-EGL: Build Date: 06/06/13 Thu
04-28 23:05:00.935 19576 19576 I Adreno200-EGL: Local Branch: 17_182_qsida
04-28 23:05:00.935 19576 19576 I Adreno200-EGL: Remote Branch: 
04-28 23:05:00.935 19576 19576 I Adreno200-EGL: Local Patches: 
04-28 23:05:00.935 19576 19576 I Adreno200-EGL: Reconstruct Branch: 
04-28 23:05:00.976 19576 19576 D OpenGLRenderer: Enabling debug mode 0
04-28 23:05:46.231 19576 19576 I Adreno200-EGL: <qeglDrvAPI_eglInitialize:269>: EGL 1.4 QUALCOMM build:  (CL2961769)
04-28 23:05:46.231 19576 19576 I Adreno200-EGL: Build Date: 06/06/13 Thu
04-28 23:05:46.231 19576 19576 I Adreno200-EGL: Local Branch: 17_182_qsida
04-28 23:05:46.231 19576 19576 I Adreno200-EGL: Remote Branch: 
04-28 23:05:46.231 19576 19576 I Adreno200-EGL: Local Patches: 
04-28 23:05:46.231 19576 19576 I Adreno200-EGL: Reconstruct Branch: 
04-28 23:05:49.839 19285 19435 I ActivityManager: START {flg=0x10000 cmp=com.moonpi.swiftnotes/.EditActivity (has extras) u=0} from pid 19576
04-28 23:06:02.608 19285 19438 I ActivityManager: START {flg=0x10000 cmp=com.moonpi.swiftnotes/.EditActivity (has extras) u=0} from pid 19576
04-28 23:06:09.420 19576 19576 D View    : Remote keyboard is shown, try to dismiss
04-28 23:06:15.012 19576 19576 D View    : Remote keyboard is shown, try to dismiss
04-28 23:06:51.320 19576 19576 D View    : Remote keyboard is shown, try to dismiss
04-28 23:06:56.456 19576 19576 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
04-28 23:06:57.206 19285 19285 I ActivityManager: START {flg=0x10000 cmp=com.moonpi.swiftnotes/.EditActivity (has extras) u=0} from pid 19576
04-28 23:06:58.253 19576 19576 E InputEventReceiver: Exception dispatching input event.
04-28 23:06:58.255 19576 19576 D AndroidRuntime: Shutting down VM
04-28 23:06:58.363 19576 19576 E AndroidRuntime: FATAL EXCEPTION: main
04-28 23:06:58.363 19576 19576 E AndroidRuntime: java.lang.IllegalArgumentException: pointerIndex out of range
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.MotionEvent.nativeGetAxisValue(Native Method)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.MotionEvent.getY(MotionEvent.java:1996)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.widget.ScrollView.onTouchEvent(ScrollView.java:588)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.View.dispatchTouchEvent(View.java:7153)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2170)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1905)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1925)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1379)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.app.Activity.dispatchTouchEvent(Activity.java:2396)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1873)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.View.dispatchPointerEvent(View.java:7333)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3178)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3123)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4159)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4138)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4230)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:180)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:4209)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:4249)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.Choreographer.doCallbacks(Choreographer.java:555)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.Choreographer.doFrame(Choreographer.java:523)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:615)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:92)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:137)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:4781)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at java.lang.reflect.Method.invokeNative(Native Method)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Method.java:511)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:568)
04-28 23:06:58.363 19576 19576 E AndroidRuntime:    at dalvik.system.NativeStart.main(Native Method)
04-28 23:07:01.885 19576 19576 I Process : Sending signal. PID: 19576 SIG: 9
04-28 23:07:01.917 19285 19285 I ActivityManager: Process com.moonpi.swiftnotes (pid 19576) has died.
04-28 23:07:02.025 19285 19296 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 19576 uid 10051
```

**Comment by adrianchifor** [comment]
Thanks for the report and the log! I will fix it and release the new version as soon as possible.

**Comment by Self-Perfection** [comment]
So, uhm, it this issue fixed?

**Comment by adrianchifor** [comment]
Project no longer maintained unfortunately. Also, this crash stopped happening a long time ago (no crash reports in Google Play Console for the last 6 months).
